/*IF NOT EXISTS (SELECT * FROM sysobjects WHERE id = object_id(N'[dbo].[COCKTAILUSER]')
AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
CREATE TABLE [dbo].[COCKTAILUSER]
(
	[CocktailUserId] NVARCHAR(50) NOT NULL PRIMARY KEY, 
    [FirstName] NVARCHAR(50) NOT NULL, 
    [LastName] NVARCHAR(50) NOT NULL, 
    [Email] NVARCHAR(50) NOT NULL, 
    [DOB] SMALLDATETIME NULL,
	[Active] BIT NULL DEFAULT 1,
    [Exp] INT NULL,
	[AvatarURL] NVARCHAR(MAX) NULL
)*/

IF NOT EXISTS (SELECT * FROM sysobjects WHERE id = object_id(N'[dbo].[ALLERGEN]')
AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
CREATE TABLE [dbo].[ALLERGEN]
(
	[AllergenId] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    [ShortName] nvarchar(50) NOT NULL,
	[LongName] nvarchar(MAX) NULL,
	[ImageURL] NVARCHAR(MAX) NULL
)

IF NOT EXISTS (SELECT * FROM sysobjects WHERE id = object_id(N'[dbo].[NUTRITIONAL_INFO]')
AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
CREATE TABLE [dbo].[NUTRITIONAL_INFO]
(
	[Nutritional_InfoId] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [ShortName] nvarchar(50) NOT NULL,
	[LongName] nvarchar(MAX) NULL
)

IF NOT EXISTS (SELECT * FROM sysobjects WHERE id = object_id(N'[dbo].[RECIPE_CATEGORY]')
AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
CREATE TABLE [dbo].[RECIPE_CATEGORY]
(
	[Recipe_CategoryId] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [Name] NVARCHAR(50) NOT NULL, 
    [Description] NVARCHAR(MAX) NULL
)

IF NOT EXISTS (SELECT * FROM sysobjects WHERE id = object_id(N'[dbo].[MEASUREMENT_UNIT]')
AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
CREATE TABLE [dbo].[MEASUREMENT_UNIT]
(
	[MeasurementUnitId] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [ShortName] nvarchar(50) NOT NULL,
	[LongName] nvarchar(MAX) NULL,
	[MlFactor] FLOAT NOT NULL DEFAULT 1,
)

IF NOT EXISTS (SELECT * FROM sysobjects WHERE id = object_id(N'[dbo].[RECIPE]')
AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
CREATE TABLE [dbo].[RECIPE]
(
	[RecipeId] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [Rating] FLOAT NULL, 
    [SubmittedDate] DATETIME NOT NULL, 
    [ModifiedDate] DATETIME NULL, 
    [Votes] INT NULL, 
    [SubmittedBy] NVARCHAR(128) NOT NULL, 
    [ModifiedBy] NVARCHAR(128) NOT NULL, 
    [Name] NVARCHAR(50) NOT NULL, 
    [Description] NVARCHAR(MAX) NULL, 
    [Category] INT NULL, 
	[ImageURL] NVARCHAR(MAX) NULL,
    CONSTRAINT [FK_RECIPE_RECIPE_CATEGORY] FOREIGN KEY ([Category]) REFERENCES [RECIPE_CATEGORY]([Recipe_CategoryId]),
	/*CONSTRAINT [FK_RECIPE_USER] FOREIGN KEY ([SubmittedBy]) REFERENCES [COCKTAILUSER]([CocktailUserId]), 
	CONSTRAINT [FK_RECIPE_USER_MOD] FOREIGN KEY ([ModifiedBy]) REFERENCES [COCKTAILUSER]([CocktailUserId])*/
)

IF NOT EXISTS (SELECT * FROM sysobjects WHERE id = object_id(N'[dbo].[INGREDIENT]')
AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
CREATE TABLE [dbo].[INGREDIENT]
(
	[IngredientId] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Name] nvarchar(50) NOT NULL,
	[Description] nvarchar(MAX) NOT NULL, 
    [DateSubmitted] DATETIME NOT NULL, 
    [DateModified] DATETIME NULL,
	[SubmittedBy] NVARCHAR(128) NOT NULL, 
    [ModifiedBy] NVARCHAR(128) NOT NULL, 
    [AlcoholPercent] FLOAT NOT NULL DEFAULT 0,
	[MeasurementUnitId] INT NOT NULL,
	[ImageURL] NVARCHAR(MAX) NULL,
	/*CONSTRAINT [FK_INGREDIENT_USER] FOREIGN KEY ([SubmittedBy]) REFERENCES [COCKTAILUSER]([CocktailUserId]), 
	CONSTRAINT [FK_INGREDIENT_USER_MOD] FOREIGN KEY ([ModifiedBy]) REFERENCES [COCKTAILUSER]([CocktailUserId]),*/
	CONSTRAINT [FK_INGREDIENT_MEASUREMENT_UNIT] FOREIGN KEY ([MeasurementUnitId]) REFERENCES [MEASUREMENT_UNIT]([MeasurementUnitId])
)

IF NOT EXISTS (SELECT * FROM sysobjects WHERE id = object_id(N'[dbo].[RECIPE_INGREDIENT]')
AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
CREATE TABLE [dbo].[RECIPE_INGREDIENT] (
    [Amount] FLOAT NOT NULL,
    [RecipeId] INT NOT NULL,
    [IngredientId] INT NOT NULL,
	CONSTRAINT [FK_RECIPE_INGREDIENT_RECIPE] FOREIGN KEY ([RecipeId]) REFERENCES [RECIPE]([RecipeId]) ON DELETE CASCADE, 
	CONSTRAINT [FK_RECIPE_INGREDIENT_INGREDIENT] FOREIGN KEY ([IngredientId]) REFERENCES [INGREDIENT]([IngredientId]) ON DELETE CASCADE,  
    CONSTRAINT [RECIPE_INGREDIENTId] PRIMARY KEY CLUSTERED ([RecipeId] ASC, [IngredientId] ASC)
)

IF NOT EXISTS (SELECT * FROM sysobjects WHERE id = object_id(N'[dbo].[RECIPE_STEP]')
AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
CREATE TABLE [dbo].[RECIPE_STEP] (
    [StepNr] INT NOT NULL,
	[Description] NVARCHAR(MAX) NULL,
    [RecipeId] INT NOT NULL,
	CONSTRAINT [FK_RECIPE_STEP_RECIPE] FOREIGN KEY ([RecipeId]) REFERENCES [RECIPE]([RecipeId]) ON DELETE CASCADE,
    CONSTRAINT [RECIPE_STEPId] PRIMARY KEY CLUSTERED ([RecipeId] ASC, [StepNr] ASC)
)

IF NOT EXISTS (SELECT * FROM sysobjects WHERE id = object_id(N'[dbo].[INGREDIENT_ALLERGEN]')
AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
CREATE TABLE [dbo].[INGREDIENT_ALLERGEN] (
    [Present] BIT NOT NULL,
	[IngredientId] INT NOT NULL,
    [AllergenId] INT NOT NULL,
	CONSTRAINT [FK_INGREDIENT_ALLERGEN_INGREDIENT] FOREIGN KEY ([IngredientId]) REFERENCES [INGREDIENT]([IngredientId]) ON DELETE CASCADE,
	CONSTRAINT [FK_INGREDIENT_ALLERGEN_ALLERGEN] FOREIGN KEY ([AllergenId]) REFERENCES [ALLERGEN]([AllergenId]) ON DELETE CASCADE,
    CONSTRAINT [INGREDIENT_ALLERGENId] PRIMARY KEY CLUSTERED ([IngredientId] ASC, [AllergenId] ASC)
)

IF NOT EXISTS (SELECT * FROM sysobjects WHERE id = object_id(N'[dbo].[INGREDIENT_NUT_INFO]')
AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
CREATE TABLE [dbo].[INGREDIENT_NUTRITIONAL_INFO] (
    [Amount] BIT NOT NULL,
	[IngredientId] INT NOT NULL,
    [Nutritional_InfoId] INT NOT NULL,
	CONSTRAINT [FK_INGREDIENT_NUTRITIONAL_INFO_INGREDIENT] FOREIGN KEY ([IngredientId]) REFERENCES [INGREDIENT]([IngredientId]) ON DELETE CASCADE,
	CONSTRAINT [FK_INGREDIENT_NUTRITIONAL_INFO_ALLERGEN] FOREIGN KEY ([Nutritional_InfoId]) REFERENCES [NUTRITIONAL_INFO]([Nutritional_InfoId]) ON DELETE CASCADE,
    CONSTRAINT [INGREDIENT_NUTRITIONAL_INFOId] PRIMARY KEY CLUSTERED ([IngredientId] ASC, [Nutritional_InfoId] ASC)
)