//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocktailAlmanac.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CocktailEntities1 : DbContext
    {
        public CocktailEntities1()
            : base("name=CocktailEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<ALLERGEN> ALLERGEN { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<INGREDIENT> INGREDIENT { get; set; }
        public virtual DbSet<INGREDIENT_ALLERGEN> INGREDIENT_ALLERGEN { get; set; }
        public virtual DbSet<INGREDIENT_NUTRITIONAL_INFO> INGREDIENT_NUTRITIONAL_INFO { get; set; }
        public virtual DbSet<MEASUREMENT_UNIT> MEASUREMENT_UNIT { get; set; }
        public virtual DbSet<NUTRITIONAL_INFO> NUTRITIONAL_INFO { get; set; }
        public virtual DbSet<RECIPE> RECIPE { get; set; }
        public virtual DbSet<RECIPE_CATEGORY> RECIPE_CATEGORY { get; set; }
        public virtual DbSet<RECIPE_INGREDIENT> RECIPE_INGREDIENT { get; set; }
        public virtual DbSet<RECIPE_STEP> RECIPE_STEP { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
    }
}
