//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocktailAlmanac.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class INGREDIENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INGREDIENT()
        {
            this.INGREDIENT_ALLERGEN = new HashSet<INGREDIENT_ALLERGEN>();
            this.INGREDIENT_NUTRITIONAL_INFO = new HashSet<INGREDIENT_NUTRITIONAL_INFO>();
            this.RECIPE_INGREDIENT = new HashSet<RECIPE_INGREDIENT>();
            this.RECIPE_STEP = new HashSet<RECIPE_STEP>();
        }
    
        public int IngredientId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        [DisplayFormat(DataFormatString = "{0:d}")]
        [Display(Name = "Date Submitted")]
        public System.DateTime DateSubmitted { get; set; }

        [DisplayFormat(DataFormatString = "{0:d}")]
        [Display(Name = "Date Modified")]
        public Nullable<System.DateTime> DateModified { get; set; }

        [Display(Name = "Submitted By")]
        public string SubmittedBy { get; set; }

        [Display(Name = "Modified By")]
        public string ModifiedBy { get; set; }

        [Display(Name = "ABV")]
        public double AlcoholPercent { get; set; }

        [Display(Name = "Default Measurement Unit")]
        public int MeasurementUnitId { get; set; }

        [Display(Name = "Image")]
        public string ImageURL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INGREDIENT_ALLERGEN> INGREDIENT_ALLERGEN { get; set; }
        public virtual MEASUREMENT_UNIT MEASUREMENT_UNIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INGREDIENT_NUTRITIONAL_INFO> INGREDIENT_NUTRITIONAL_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECIPE_INGREDIENT> RECIPE_INGREDIENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECIPE_STEP> RECIPE_STEP { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
    }
}
