//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocktailAlmanac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INGREDIENT_ALLERGEN
    {
        public bool Present { get; set; }
        public int IngredientId { get; set; }
        public int AllergenId { get; set; }
    
        public virtual ALLERGEN ALLERGEN { get; set; }
        public virtual INGREDIENT INGREDIENT { get; set; }
    }
}
