//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocktailAlmanac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INGREDIENT_NUTRITIONAL_INFO
    {
        public bool Amount { get; set; }
        public int IngredientId { get; set; }
        public int Nutritional_InfoId { get; set; }
    
        public virtual INGREDIENT INGREDIENT { get; set; }
        public virtual NUTRITIONAL_INFO NUTRITIONAL_INFO { get; set; }
    }
}
