//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocktailAlmanac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INGREDIENT_NUTRITIONAL_INFO
    {
        public bool Amount { get; set; }
        public int IngredientId { get; set; }
        public int Nutritional_InfoId { get; set; }
    
        public virtual INGREDIENT INGREDIENT { get; set; }
        public virtual NUTRITIONAL_INFO NUTRITIONAL_INFO { get; set; }
    }
}
