//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocktailAlmanac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECIPE_STEP
    {
        public string Description { get; set; }
        public int RecipeId { get; set; }
        public int StepNr { get; set; }
    
        public virtual RECIPE RECIPE { get; set; }
    }
}
